services:
  - type: web
    name: miau-store
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService:
          type: web
          name: miau-store
          property: port
      - key: MONGODB_URI
        value: mongodb+srv://23202001:23202001@cluster0.vgypvgq.mongodb.net/catstore?retryWrites=true&w=majority&appName=Cluster0
      - key: JWT_SECRET
        value: miau_store_jwt_secret_key_2024_secure_random_string
